# Generated by Django 3.1.3 on 2020-12-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
