# Generated by Django 3.1.3 on 2020-12-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0002_auto_20201201_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user1',
            options={'verbose_name': '유저', 'verbose_name_plural': '유저'},
        ),
        migrations.AddField(
            model_name='user1',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
